config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resource  :dashboard, only: [:show]
    resources :users,     only: [:update, :destroy, :create, :new, :edit]
    resources :families, only: [:show, :new, :create, :index, :edit, :update]
  end

  resources :families, only: [:index, :show]

  resources :users, only: [:new, :create, :edit, :update]

  resources :cart, only: [:index]

  resources :cart_items, only: [:create, :update, :destroy]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: "users#show"

  resources :donations, only: [:index, :show, :new, :create]

  resources :loans, only: [:show, :edit, :update, :new, :create]

  root to: "homes#show"

  resources :charities, only: [:index, :edit, :new, :create]
  patch '/charities/:id', to: "charities#update"

  get ':charity_slug', to: 'charities#show', as: :charity

  namespace :charity, path: ':charity_slug', as: :charity do
    resources :families, only: [:index]
    resources :dashboard, only: [:show]
  end

  scope :category do
    get ':categories_slug', to: 'categories#show', as: :category
  end
end

app/models/family.rb
class Family < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :arrival_date, presence: true
  validates :num_married_adults, presence: true
  validates :num_unmarried_adults, presence: true
  validates :num_children_over_two, presence: true
  validates :num_children_under_two, presence: true
  validates :donation_deadline, presence: true

  has_many :category_families
  has_many :categories, through: :category_families
  has_many :supply_items
  has_many :supplies, through: :supply_items
  has_many :donation_items, through: :supply_items
  has_one :loan
  belongs_to :nationality
  belongs_to :charity

  has_attached_file :family_photo, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>',
    large: '600x600>'
  }

  validates_attachment_content_type :family_photo, :content_type => /\Aimage\/.*\Z/

  scope :retired, -> {where("arrival_date < ?", Date.today)}
  scope :active, -> {where("arrival_date > ?", Date.today)}

  def num_people
    num_married_adults + num_unmarried_adults +
    num_children_over_two + num_children_under_two
  end

  def num_adults
    num_married_adults + num_unmarried_adults
  end

  def supply_quantity_hash
    {"adult" => num_adults,
     "person" => num_people,
     "household" => 1,
     "baby" => num_children_under_two,
     "child" => num_children_over_two,
     "other" => 0}
  end

  def create_supply_items
    Supply.all.each do |supply|
      if supply_quantity_hash[supply.multiplier_type] != 0
        supply_items.create(supply: supply, quantity: supply_quantity_hash[supply.multiplier_type])
      end
    end
  end

  def value_of_supplies_needed
    supply_items.reduce(0) do |sum, supply_item|
      sum + (supply_item.supply.value * supply_item.quantity)
    end
  end

  def value_of_supplies_purchased
    value = 0
    supply_items.each do |supply_item|
      supply_item.donation_items.each do |donation_item|
        value += donation_item.quantity * supply_item.supply.value
      end
    end
    value
  end

  def percentage_donated
    if value_of_supplies_needed == 0|| value_of_supplies_purchased == 0
      return 0
    else
      ((value_of_supplies_purchased / value_of_supplies_needed) * 100).to_i
    end
  end

  def retired?
    arrival_date <= Date.today
  end

  def donations_received
    donation_items
  end
end

app/controllers/admin/families_controller.rb
class Admin::FamiliesController < Admin::BaseController

  def index
    @families = Family.all
    @nationalities = Nationality.all
  end

  def show
    @family = Family.find(params[:id])
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(family_params)
    if @family.save
      @family.create_supply_items
      flash[:success] = "Family with last name, #{@family.last_name}, created!"
      url = "https://refugeerestart.herokuapp.com/families/#{@family.id}"
      redirect_to admin_family_path(@family)
    else
      flash.now[:warning] = @family.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @family = Family.find(params[:id])
  end

  def update
    family = Family.find(params[:id])
    if family.update(family_params)
     flash[:success] = "Your updates have been saved"
     redirect_to admin_dashboard_path
   else
     flash.now[:warning] = @family.errors.full_messages.join(", ")
     render :edit
   end
  end

  private

  def family_params
    params.require(:family).permit(
                                   :first_name,
                                   :last_name,
                                   :arrival_date,
                                   :num_married_adults,
                                   :num_unmarried_adults,
                                   :num_children_over_two,
                                   :num_children_under_two,
                                   :donation_deadline,
                                   :nationality_id,
                                   :description,
                                   :family_photo
                                   )
  end
end

app/controllers/charity/families_controller.rb
class Charity::FamiliesController < ApplicationController
  def index
    @featured = Nationality.get_random
    @nationalities = Nationality.all
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController

  def index
    @families = Family.all
    @featured = Nationality.get_random
    @nationalities = Nationality.all
  end

  def show
    @family = Family.find(params[:id])
  end
end

app/views/families/index.html.erb
<div class="container">
<h1 class='col-sm-10 col-sm-offset-1'>Help Welcome these Families to the United States</h1>

<div class="well col-sm-10 col-sm-offset-1">
  <div class="container">
    <div class="col-sm-5 photo">
      <%= image_tag @featured.photo_path, :class => "img-responsive center-block" %>
    </div>
    <div class="col-sm-4 details">
      <p><%= link_to "Learn more about the #{@featured.name} conflict", @featured.info_link, class: "center-block learn-more" %></p>
      <%= image_tag @featured.greeting, :class => "img-responsive center-block greeting" %>
      <h4>Welcome to America<h4>
      </div>
    </div>
  </div>
</div>
<div class="container">
<br>

<div class="nationality">
<% @nationalities.each do |nationality| %>
  <div class="row <%=nationality.name%>">
    <h4> <%= nationality.name %> Families Arriving Soon:</h4>
    <%= render partial: 'shared/confidential_family_list', locals: {families: nationality.families.active} %>
  </div>
<% end %>
</div>

<h2 class="text-center">Want to know more about the conflict? Click a country below.</h2>
<div class="col-md-8 col-md-offset-2" id="mapid"></div>
</div>

app/views/families/show.html.erb
<%= render partial: 'shared/family_show_headings'%>

<div class="profile">

  <%= render partial: 'shared/family_show_nationality_info', locals: {photo: @family.nationality.photo_path}%>

    <div class="family-info">
        <table class="table">
          <tr><td>Married Adults: <%= @family.num_married_adults %></td>
          <td>Unmarried Adults: <%= @family.num_unmarried_adults %></td></tr>
          <tr><td>Children Over Two: <%= @family.num_children_over_two %></td>
          <td>Children Under Two: <%= @family.num_children_under_two %></td></tr>
        </table>
    </div>
  </div>
</div>

<div class="col-sm-10 col-sm-offset-1">

  <% present @family do |family_presenter|  %>
    <%= family_presenter.retired_or_active_progress_bar %>
  <% end %>

  <h5><%= currency @family.value_of_supplies_purchased %> has been donated.</h5>
  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuemin="0"
        aria-valuemax="100" style="min-width: 2em; width: <%= @family.percentage_donated %>%;">
      <%= @family.percentage_donated %>%
    </div>
  </div>

<% if @family.loan && @family.loan.active? %>
<h4>This family has requested a Microloan to begin a business of their own</h4>
<table class="table">
  <tr>
    <th>Loan Purpose</th>
    <th>Requested Amount</th>
    <th>Donation Amount</th>
    <th></th>
    <th></th>
  </tr>

    <%= form_for @family.loan, url: cart_items_path, method: :create do |f| %>
      <div class='<%= @family.last_name%>-loan-info table-info' >
      <tr>
        <td><%= @family.loan.purpose %></br>
        <td><%= currency(@family.loan.requested_amount) %></td>
        <td><%= f.hidden_field :id, :value => @family.loan.id %>
          <div class="form-group">
            <%= f.select(:requested_amount, (@family.loan.donation_range), { :prompt => '0'}, { class: 'form-control' }) %>
          </div>
        </td>
        <td><%= f.submit 'add to cart', class: "btn btn-warning"%></td>
        <td>
          <div class="tags">
            <%= link_to "View Loan", loan_path(@family.loan), class: "btn btn-inverse" %>
          </div>
        </td>
      </tr>
      </div>
    <% end %>
</table>

<% end %>

<% if !@family.retired? %>
  <h4>Welcome this family with the following donations:</h4>
  <table class="table">
    <tr>
      <th>Donation Item</th>
      <th>Donation Value</th>
      <th>Quantity</th>
      <th></th>
    </tr>

    <% @family.supply_items.each do |supply_item| %>
    <% if supply_item.quantity_remaining > 0 %>
      <%= form_for supply_item, url: cart_items_path, method: :create do |f| %>
        <div class='<%= supply_item.name %> table-info' >
        <tr>
          <td><%= supply_item.name %></br>
          <em><%= supply_item.description %></em></td>
          <td><%= currency(supply_item.value) %></td>
          <td><%= f.hidden_field :id, :value => supply_item.id %>
            <div class="form-group">
              <%= f.select(:quantity, (1..supply_item.quantity_remaining), { :prompt => '0'}, { class: 'form-control' }) %>
            </div>
          </td>
          <td class="add-to-cart"><%= f.submit 'add to cart', class: "btn btn-warning"%></td>
        </tr>
        </div>
      <% end %>
      <% end %>
    <% end  %>
  </table>
<% else %>
  <h4>This family was welcomed with the following donations:</h4>
    <table class="table arrived-family-donations">
      <tr>
        <th>Donated Item</th>
        <th>Donated Quantity</th>
        <th>Donation Date</th>
      </tr>
      <% @family.donations_received.map do |donation_item| %>
        <tr>
          <td><%= donation_item.name %></td>
          <td><%= donation_item.quantity %></td>
          <td><%= format_date donation_item.created_at %></td>
        </tr>
      <% end %>
    </table>
<% end  %>