config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resource  :dashboard, only: [:show]
    resources :users,     only: [:update, :destroy, :create, :new, :edit]
    resources :families, only: [:show, :new, :create, :index, :edit, :update]
  end

  resources :families, only: [:index, :show]

  resources :users, only: [:new, :create, :edit, :update]

  resources :cart, only: [:index]

  resources :cart_items, only: [:create, :update, :destroy]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: "users#show"

  resources :donations, only: [:index, :show, :new, :create]

  resources :loans, only: [:show, :edit, :update, :new, :create]

  root to: "homes#show"

  resources :charities, only: [:index, :edit, :new, :create]
  patch '/charities/:id', to: "charities#update"

  get ':charity_slug', to: 'charities#show', as: :charity

  namespace :charity, path: ':charity_slug', as: :charity do
    resources :families, only: [:index]
    resources :dashboard, only: [:show]
  end

  scope :category do
    get ':categories_slug', to: 'categories#show', as: :category
  end
end

app/views/shared/_admin_box_display.html.erb
<div class="search-font filter">
    <label>Filter By Username  </label>
    <input type="text" placeholder="Username" id="user_filter_username">
</div>

<div class="box">
  <%= link_to "Create New Admin", new_admin_user_path, class: "btn button-indigo" %>
</div>

<div class="col-sm-12 col-sm-offset-1 users">
  <% admins.each do |admin| %>
    <div data-username="<%= admin.username %>"class="form-box col-sm-5 user">
      <div class="white-texxt">
        <%= admin.username %>,
        <%= charity_exists(admin) %>
      </div>
      <div>
        <%= form_for [:admin, admin], multipart: true do |f|  %>
          <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :cell %>
            <%= f.telephone_field :cell, class: "form-control" %>
          </div>

        <%= f.submit "Update Admin", class: "btn btn-info active" %>
        <% end %>
        <div class="col-sm-2">
          <%= button_to "Remove Admin", admin_user_path(admin), method: :delete,  class: "btn btn-warning active btn-xs" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_confidential_family_list.html.erb
<ul class="list-group">
  <% families.each do |family| %>
  <div class='col-md-6'>
    <li class="list-group-item"><%= link_to "#{family.nationality.name} Family of #{family.num_people}", family_path(family) %>: arriving in <%= days_from_today family.arrival_date %></li>
  </div>
  <% end %>
</ul>

app/views/shared/_family_show_headings.html.erb
<div>
  <h1 class="family-heading col-sm-offset-1"><%= @family.nationality.name %> Family of <%= @family.num_people %></h1>

  <div class="tags">
    <% if @family.categories %>
      <% @family.categories.take(2).each do |category| %>
        <%= link_to category.name, category_path(category), class: "btn btn-inverse" %>
      <% end %>
    <% end %>
  </div>
</div>
<h4 class="col-sm-5 col-sm-offset-1 details arrival-date">Arrival Date:
  <% if @family.retired? %>
    <h4 id="family-arrived">Family Arrived</h4></h4>
  <% else %>
    <%= format_date @family.arrival_date%></h4>
    <h4 class="col-sm-5 col-sm-offset-1 details donate-by">Donate by: <%= format_date @family.donation_deadline %>
    </h4>
<% end %>

app/views/shared/_family_show_nationality_info.html.erb
<div class="col-sm-6 col-sm-offset-1 photo">
  <%= image_tag photo, :class => "img-responsive center-block" %>
  <p> <%=  @family.description %> </p>
</div>

<div class="col-sm-4 details">

  <div class="greeting">
    <%= image_tag @family.nationality.greeting, :class => "img-responsive center-block" %>
    <p>Welcome to America</p>
  </div>

  <div class="learn-more">
    <%= link_to "Learn more about the #{@family.nationality.name} conflict", @family.nationality.info_link %>
  </div>