config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resource  :dashboard, only: [:show]
    resources :users,     only: [:update, :destroy, :create, :new, :edit]
    resources :families, only: [:show, :new, :create, :index, :edit, :update]
  end

  resources :families, only: [:index, :show]

  resources :users, only: [:new, :create, :edit, :update]

  resources :cart, only: [:index]

  resources :cart_items, only: [:create, :update, :destroy]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: "users#show"

  resources :donations, only: [:index, :show, :new, :create]

  resources :loans, only: [:show, :edit, :update, :new, :create]

  root to: "homes#show"

  resources :charities, only: [:index, :edit, :new, :create]
  patch '/charities/:id', to: "charities#update"

  get ':charity_slug', to: 'charities#show', as: :charity

  namespace :charity, path: ':charity_slug', as: :charity do
    resources :families, only: [:index]
    resources :dashboard, only: [:show]
  end

  scope :category do
    get ':categories_slug', to: 'categories#show', as: :category
  end
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  validates :status, presence: true, inclusion: %w(Pledged Received Cancelled)

  belongs_to :user
  has_many :donation_items

  def date
    created_at.to_date
  end

  def total
    donation_items.reduce(0) do |sum, item|
      sum += item.subtotal
    end
  end

  def self.stats
    num_items = DonationItem.total_items
    num_families = Family.count
    money_raised =  Donation.all.reduce(0) do |sum, donation|
      sum += donation.total
    end
    {num_items: num_items, num_families: num_families, money_raised: money_raised.to_f}
  end

  def create_donation_item(cart_item, donation)
    if cart_item["class_type"] == "Loan"
      DonationItem.create(quantity: cart_item["quantity"],
                          loan: Loan.find(cart_item["id"]),
                          donation: donation)
    else
      DonationItem.create(quantity: cart_item["quantity"],
                          supply_item: SupplyItem.find(cart_item["id"]),
                          donation: donation)
    end
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def index
    if !current_user
      flash[:info] = "Please login to see your donation history."
      redirect_to login_path
    else
      @donations = current_user.donations
    end
  end

  def show
    @donation = Donation.find(params[:id])
    if @donation.user != current_user
      flash[:info] = "No donation found."
      redirect_to root_path
    end
  end

  def new
    @cart_items = @cart.get_cart_item_list
  end

  def create
    cart_items = @cart.contents
    @donation = Donation.new(user_id: current_user.id, status: "Pledged")
    if @donation.save
      cart_items.each do |cart_item|
        @donation.create_donation_item(cart_item, @donation)
      end
      flash[:success] = "Your donation (ID#: #{@donation.id}) was received. Thank you!"
      session[:cart] = []
      redirect_to donations_path
    else
      flash.now[:warning] = "Something went wrong with your donation confirmation."
      render :new
    end
  end
end

app/views/donations/index.html.erb
<div class="container">

<h2><%= current_user.username %>'s Donations</h2>
<p>Total Donations: <%= @donations.count %> </p>

<table class="table">
  <tr>
    <th>Donation ID:</th>
    <th>Status:</th>
    <th>Placed on:</th>
    <th>Benefitting Families:</th>
    <th>Donation Items:</th>
  </tr>
  <% @donations.each do |donation| %>
    <tr>
      <td> <%= link_to donation.id, donation_path(donation.id) %></td>
      <td id="donation-status"> <%= donation.status %> </td>
      <td> <%= donation.date %></td>
      <td class="family-info">
      <% donation.donation_items.each do |donation_item| %>
        <%= donation_item.family_description %></br>
      <% end %>
      </td>
      <td class="donation-item-info">
      <% donation.donation_items.each do |donation_item| %>
        <% if donation_item.supply_item %>
          <%= donation_item.quantity %>
          <%= donation_item.name %></br>
        <% else %>
          <%= currency(donation_item.quantity) %>
          <%="#{donation_item.name} loan"%></br>
        <% end %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/donations/new.html.erb
<div class="container">
<h1>Confirm Your Donation</h1>

<table class="table">
  <tr>
    <th>Item</th>
    <th>Description</th>
    <th>Value</th>
    <th>Donated Quantity</th>
    <th>Subtotal</th>
  </tr>
  <% @cart_items.each do |cart_item| %>
  <% if cart_item.class != LoanDecorator %>
      <tr class= '<%=cart_item.name%>'>
        <td><%= cart_item.name %></td>
        <td><%= cart_item.description %></td>
        <td><%= currency(cart_item.value) %></td>
        <td><%= cart_item.supply_item_quantity %></td>
        <td><%= currency(cart_item.value * cart_item.supply_item_quantity.to_i)%></td>
      </tr>
  <% else %>
    <tr>
      <td><%= "#{cart_item.purpose} loan"%></td>
      <td><%= truncate(cart_item.description, length: 40) %></td>
      <td><%= currency(cart_item.requested_amount) %></td>
      <td><%= currency(cart_item.quantity) %></td>
      <td><%= currency(cart_item.quantity.to_i)%></td>
    </tr>
  <% end %>
<% end %>
</table>

<h2>Total: <%= number_to_currency @cart.total_price %> </h2>

<%= link_to "Back To Your Cart", cart_index_path, class: "btn btn-info" %>

<%= link_to "Confirm Donation", donations_path, method: :post, class: "btn btn-success" %>
</div>

app/views/donations/show.html.erb
<div class="container">
<h2>Donation ID: <%= @donation.id %> </h2>
<h4>Placed on: <%= @donation.date %></h4>
<h4 id="donation-status">Status: <%= @donation.status %></h4>
<h4 id="donation-total">Total: <%= currency(@donation.total) %> </h4>
<% if @donation.status != "Pledged" %>
<h4 id="donation-updated">Updated on: <%= @donation.updated_at.to_date %></h4>
<% end %>

<table class="table">
  <tr>
    <th>Benefitting Families:</th>
    <th>Donation Item:</th>
    <th>Quantity:</th>
    <th>Value:</th>
    <th>Subtotal:</th>
  </tr>

  <% @donation.donation_items.each do |donation_item| %>
  <tr class='<%= donation_item.name%>-info'>
    <td>
      <% if donation_item.supply_item %>
        <%= link_to donation_item.family_description, family_path(donation_item.supply_item.family) %>
        <td><%= donation_item.name %></td>
        <td><%= donation_item.quantity %></td>
      <% else %>
        <%= link_to donation_item.family_description, family_path(donation_item.loan.family) %>
        <td><%="#{donation_item.name} loan"%></td>
        <td><%= currency(donation_item.quantity) %></td>
      <% end %></td>
    <td><%= currency(donation_item.value) %></td>
    <td><%= currency(donation_item.subtotal) %></td>
  </tr>
  <% end %>
</table>

<% if current_admin? %>
  <%= link_to "Back to my Dashboard", admin_dashboard_path(current_user) %>
<% else %>
  <%= link_to "Back to my Dashboard", dashboard_path(current_user) %>
<% end %>
</div>