config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resource  :dashboard, only: [:show]
    resources :users,     only: [:update, :destroy, :create, :new, :edit]
    resources :families, only: [:show, :new, :create, :index, :edit, :update]
  end

  resources :families, only: [:index, :show]

  resources :users, only: [:new, :create, :edit, :update]

  resources :cart, only: [:index]

  resources :cart_items, only: [:create, :update, :destroy]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: "users#show"

  resources :donations, only: [:index, :show, :new, :create]

  resources :loans, only: [:show, :edit, :update, :new, :create]

  root to: "homes#show"

  resources :charities, only: [:index, :edit, :new, :create]
  patch '/charities/:id', to: "charities#update"

  get ':charity_slug', to: 'charities#show', as: :charity

  namespace :charity, path: ':charity_slug', as: :charity do
    resources :families, only: [:index]
    resources :dashboard, only: [:show]
  end

  scope :category do
    get ':categories_slug', to: 'categories#show', as: :category
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  def show
    @admins = User.all_admins
    @charities = Charity.all
  end
end

app/controllers/charity/dashboard_controller.rb
class Charity::DashboardController < ApplicationController
  def show
    @admins = current_user.charity_admins(current_charity)
  end
end

app/views/admin/dashboards/_charity_status.html.erb
<%= form_for charity, url: "/charities/#{charity.id}" do |f| %>
  <div class="row">
    <%= f.label :status, "Status" %>
    <%= f.select :status, options_for_select(["online", "offline", "pending"], "#{charity.status}"), {}, class: "small-search" %>
    <%= f.submit "Update Status", class: "btn btn-default btn-xs" %>
 </div>
<% end %>

app/views/admin/dashboards/_padmin.html.erb
<% if charity_type %>
<div class="container">
  <div class="details">
    <h2> <%= charity_header(charity_type) %> </h2>
  </div>
  <% charity_type.each do |charity| %>
  <div class="well col-sm-10 col-sm-offset-1">
    <div class="container">
       <div class = "<%= charity.name %>">
      <div class="col-sm-4 details">
        <p><%= link_to charity.name, charity_path(charity.slug), class: "center-block learn-more" %></p>
        <p><%= button_to "Update Charity", edit_charity_path(charity), method: :get, class: "center-block btn update-charity" %></p>
        <p><%= render partial: 'charity_status', locals: {charity: charity} %></p>
      </div>
      <div class="col-sm-5 families-box">
        <div class="grey-texxt">
          Families
        </div>
        <div class="active-families">
            <%= render partial: 'padmin_family_list', locals: {families: charity.families.active, current: true}%>
        </div>
        <%= render partial: 'padmin_family_list', locals: {families: charity.families.retired, current: false}%>
      </div>
    </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/admin/dashboards/_padmin_family_list.html.erb
<div class = "families-table">

  <table class="table table-hover">
    <% families.each do |family| %>

    <tr class= "<%= family.last_name %>">
      <% if current %>
          <td><%= link_to "#{family.last_name}, #{family.first_name}", admin_family_path(family) %>: arriving in <%= days_from_today family.arrival_date %></td>
          <td><%= render partial: "admin/families/loan_information", locals: {family: family} %></td>
          <td><%= button_to "Update Family", edit_admin_family_path(family), method: :get, class: "btn btn-warning btn-xs" %></td>
      <% else %>
          <td><%= link_to "#{family.last_name}, #{family.first_name}", admin_family_path(family) %>: arrived <%= days_from_today family.arrival_date %> ago</td>
          <td><%= render partial: "admin/families/loan_information", locals: {family: family} %></td>
          <td><%= button_to "Update Family", edit_admin_family_path(family), method: :get, class: "btn btn-warning btn-xs" %></td>
      <% end %>
    </tr>

    <% end %>
  </table>
</div>

app/views/admin/dashboards/show.html.erb
  <h1>Admin Dashboard</h1>

<div class="btn-group">
  <%= link_to "See my donations", donations_path, class: "btn btn-warning" %>
  <%= link_to "Update my profile", edit_user_path(current_user), class: "btn btn-warning" %>
  <button type="button" class="btn btn-default" id="pending">Pending Charities</button>
  <button type="button" class="btn btn-default" id="online">Online Charities</button>
  <button type="button" class="btn btn-default" id="offline">Offline Charities</button>
  <button type="button" class="btn button-indigo active" id="administrators">Manage Administrators</button>
</div>

<div class="charities hidden" id="padmin-pending">
  <div class = "pending">
    <%= render partial: 'padmin', locals: {charity_type: @charities.pending_charities} %>
  </div>
</div>

<div class="charities hidden" id="padmin-online">
  <div class = "online">
    <%= render partial: 'padmin', locals: {charity_type: @charities.online_charities} %>
  </div>
</div>

<div class="charities hidden" id="padmin-offline">
  <div class = "offline">
    <%= render partial: 'padmin', locals: {charity_type: @charities.offline_charities} %>
  </div>
</div>

<div class="charities hidden" id="all-admins">
  <div class="details">
    <%= render partial: 'shared/admin_box_display', locals: {admins: @admins} %>
  </div>
</div>